spring.application.name=Pet-Project-CRUD-App

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/PET_CRUD_APP
spring.datasource.username=postgres
spring.datasource.password=rootroot

# JPA configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.defer-datasource-initialization=true

# Server port
server.port=8080

# Optional: ??? ???????
logging.level.org.hibernate.SQL=DEBUG

# ????????? ?????????????? ?????????????
spring.sql.init.mode=never